name: "06 - Contexts"
on: 
  - push
  - workflow_dispatch
run-name: "My custom workflow run name - ${{ runner.os }}"
jobs:
  echo-data:
    runs-on: ubuntu-latest
    steps:
      - name: "Display Information"
        run: |
          echo "Event name: "
          echo "Ref: "
          echo "SHA: "
          echo "Actor: "
          echo "Workflow: "
          echo "Run ID: "
          echo "Run number: "
      - name: "Retrieve Variable"
        run: |
          echo "${{ MY_VAR }}"